import os
from dotenv import load_dotenv

load_dotenv()

RAW_DATA = os.getenv("RAW_DATA")
EVALUATION_TEST_DATA = os.getenv("EVALUATION_TEST_DATA")
MODEL_TRAINING_DATA = os.getenv("MODEL_TRAINING_DATA")
TRAINED_KMEANS_CLUSTERER = os.getenv("TRAINED_KMEANS_CLUSTERER")
TRAINED_DBSCAN_CLUSTERER = os.getenv("TRAINED_DBSCAN_CLUSTERER")
TRAINED_HIERARCHICAL_CLUSTERER = os.getenv("TRAINED_HIERARCHICAL_CLUSTERER")
TRAINED_KMEANS_FEATURES = os.getenv("TRAINED_KMEANS_FEATURES")
TRAINED_DBSCAN_FEATURES = os.getenv("TRAINED_DBSCAN_FEATURES")
TRAINED_HIERARCHICAL_FEATURES = os.getenv("TRAINED_HIERARCHICAL_FEATURES")
MINIO_CONSOLE_ADDRESS = os.getenv("MINIO_CONSOLE_ADDRESS")
MINIO_ROOT_USER = os.getenv("MINIO_ROOT_USER")
MINIO_ROOT_PASSWORD = os.getenv("MINIO_ROOT_PASSWORD")
MINIO_BUCKET = os.getenv("MINIO_BUCKET")
MINIO_PATH = os.getenv("MINIO_PATH")
MLFLOW_TRACKING_URI = os.getenv("MLFLOW_TRACKING_URI")
PIP_REQUIREMENTS = os.getenv("PIP_REQUIREMENTS")