import os
from dotenv import load_dotenv

load_dotenv()

RAW_DATA = os.getenv("RAW_DATA")
EVALUATION_TEST_DATA = os.getenv("EVALUATION_TEST_DATA")
MODEL_TRAINING_DATA = os.getenv("MODEL_TRAINING_DATA")
TRAINED_KMEANS_CLUSTERER = os.getenv("TRAINED_KMEANS_CLUSTERER")
TRAINED_DBSCAN_CLUSTERER = os.getenv("TRAINED_DBSCAN_CLUSTERER")
TRAINED_HIERARCHICAL_CLUSTERER = os.getenv("TRAINED_HIERARCHICAL_CLUSTERER")
TRAINED_KMEANS_FEATURES = os.getenv("TRAINED_KMEANS_FEATURES")
TRAINED_DBSCAN_FEATURES = os.getenv("TRAINED_DBSCAN_FEATURES")
TRAINED_HIERARCHICAL_FEATURES = os.getenv("TRAINED_HIERARCHICAL_FEATURES")

